# Generated by Django 3.0.4 on 2020-10-06 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
